# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 356512923e7cbe9be7c4d7e8c7a2c725a6d1a4aeb59504bf0dae4e8919372c4ab5491f6b60816250948c2b231afb8864d8e3677108bb6df9fe3f0d9f9cc91850

test:
  secret_key_base: 28b3e12a7e4aa6af5874c2ddc6c30b69d0705065a7bce393d35b9e7be156c7dc9a1c3e1da973d065170bcdeed045fbbd7a445ddb7f034306cc6dff5afc9ebfda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
